AwesomeAssertions/AwesomeAssertions

README.md

chore: add sonar badge

---

Src/FluentAssertions/FluentAssertions.csproj

This pull request includes a small change to the `Src/FluentAssertions/FluentAssertions.csproj` file. The change adds the company and product information to the project properties.
* [`Src/FluentAssertions/FluentAssertions.csproj`](diffhunk://#diff-119c712118df78a7cad26394b798b2ab923aafa405610a2d4a39b14a91be03dcR16-R17): Added `<Company>` and `<Product>` properties to the project file.

chore: add Company and Product metadata to FluentAssertions.csproj

---

.github/ISSUE_TEMPLATE/01_bug_report.yml
.github/ISSUE_TEMPLATE/config.yml
.github/PULL_REQUEST_TEMPLATE.md
CONTRIBUTING.md
README.md
Src/FluentAssertions/Configuration/GlobalEquivalencyOptions.cs
Src/FluentAssertions/Equivalency/EquivalencyPlan.cs
Src/FluentAssertions/Equivalency/EquivalencyValidator.cs
Src/FluentAssertions/Formatting/Formatter.cs
Src/FluentAssertions/Formatting/FormattingOptions.cs
docs/README.md

Update documentation urls to custom domain

---

docs/_pages/releases.md

Add release changelog

---

Src/FluentAssertions/Execution/AssertionScope.cs
Tests/FluentAssertions.Equivalency.Specs/AssertionRuleSpecs.cs
Tests/FluentAssertions.Specs/Execution/AssertionChainSpecs.MessageFormating.cs
Tests/FluentAssertions.Specs/Execution/AssertionScopeSpecs.cs

Distinguish between implicitly and explicitly created scopes (#58)

---

Tests/FluentAssertions.Equivalency.Specs/SelectionRulesSpecs.Accessibility.cs

Improve test for normal vs explicitly implemented properties (#29)

---

docs/_pages/releases.md

Add missing release notes for 8.0.2

Add missing release note entries

---

Src/FluentAssertions/FluentAssertions.csproj

Add the README to the nuget package

---

renovate.json

Slow down the PR rate to once a week, especially because of the tight release cycle of TUnit

Schedule the Renovate updates

---

Src/FluentAssertions/Formatting/PropertyInfoFormatter.cs

Remove unnecessary `null` check

---

docs/_config.yml

Correctly enable lunr search in docs

---

Tests/FluentAssertions.Equivalency.Specs/SelectionRulesSpecs.MemberHiding.cs
docs/_pages/dictionaries.md
docs/_pages/enums.md
docs/_pages/extensibility.md
docs/_pages/fsharp.md
docs/_pages/nullabletypes.md
docs/_pages/objectgraphs.md
docs/_pages/releases.md
docs/_pages/streams.md

Minor documentation improvements

---

Src/FluentAssertions/FluentAssertions.csproj

* Update nuget package authors to reflect the changed responsibility, but keeping the credits for the former authors #110
Fixes #110

Update nuget package authors

---

docs/_pages/releases.md

Update 8.1.0 release notes in docs

---

Src/FluentAssertions/FluentAssertions.csproj

chore: Update package copyright

---

docs/_pages/releases.md

Update release notes for 8.2.0

---

docs/_pages/releases.md

When this PR is merged I would release 9.0.0

Bump release version in docs

---

docs/_pages/introduction.md
docs/_pages/objectgraphs.md

Minor documentation fixes

---

Src/AwesomeAssertions/Primitives/StringEqualityStrategy.cs
Tests/AwesomeAssertions.Equivalency.Specs/AssertionRuleSpecs.cs
Tests/AwesomeAssertions.Equivalency.Specs/BasicSpecs.cs
Tests/AwesomeAssertions.Equivalency.Specs/CollectionSpecs.cs
Tests/AwesomeAssertions.Equivalency.Specs/DictionarySpecs.cs
Tests/AwesomeAssertions.Equivalency.Specs/NestedPropertiesSpecs.cs
Tests/AwesomeAssertions.Equivalency.Specs/SelectionRulesSpecs.Basic.cs
Tests/AwesomeAssertions.Equivalency.Specs/SelectionRulesSpecs.Excluding.cs
Tests/AwesomeAssertions.Equivalency.Specs/SelectionRulesSpecs.Including.cs
Tests/AwesomeAssertions.Specs/Collections/GenericCollectionAssertionOfStringSpecs.AllSatisfy.cs
Tests/AwesomeAssertions.Specs/Collections/GenericCollectionAssertionOfStringSpecs.BeEquivalentTo.cs
Tests/AwesomeAssertions.Specs/Collections/GenericCollectionAssertionOfStringSpecs.SatisfyRespectively.cs
Tests/AwesomeAssertions.Specs/Collections/GenericDictionaryAssertionSpecs.ContainValue.cs
Tests/AwesomeAssertions.Specs/Execution/AssertionChainSpecs.MessageFormating.cs
Tests/AwesomeAssertions.Specs/Execution/AssertionScopeSpecs.ScopedFormatters.cs
Tests/AwesomeAssertions.Specs/Primitives/StringAssertionSpecs.Be.cs
Tests/AwesomeAssertions.Specs/Primitives/StringAssertionSpecs.BeEquivalentTo.cs
docs/_pages/releases.md

Improve string comparison visualization

---

renovate.json

Exclude xunit.v3* from updates

---

.github/release.yml
renovate.json

Add dependencies to own changelog category

---

README.md

Remove obsolete question from faq

---

docs/assets/css/main.scss

Fix documentation tips formatting
